version: "3.8"
services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: cloud_db

  app:
    build: .
    volumes:
      - ./:/app
    restart: always
    ports:
      - "80:8000"
    image: app:latest
    container_name: cloud_app
    command: >
      sh -c "sleep 5 &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

volumes:
  pgdata: